### PR TITLE
Input rework

### PR DESCRIPTION
**Pull request by Ryzee119**
Created as draft for author input. It reworks all the input code to be simpler. It fixes the keyboard remapping issues and gamecontroller hotplugging now works. If the user has multiple gamecontrollers connected any of them will work too.

It also adds rumble support which is now present in SDL2. Tested with Pokemon Pinball!

I have removed the sdl_joystick event stuff as the gamecontroller API is much simpler and provides a much more standard interface, and supports [99% of user controllers](https://github.com/libsdl-org/SDL/blob/main/src/joystick/SDL_gamecontrollerdb.h). Because of this, It doesnt have the same remapping flexibility as the keyboard.

The analog stick as a dpad input is not present at the moment. happy to add that in a follow up PR

### CODE REVIEW

**Comment by AlexOberhofer** [comment]
Ryzee, this looks great! Much cleaner than what I had before and its great to see you were able to get rumble working and rebinding fixed. I haven't had time to test it yet, so let me know if there's anything else you want to add into this PR (like using the joystick to emulate the dpad) - Otherwise I'll play with this a bit and merge it in when I get a chance :)

**Comment by AlexOberhofer** [comment]
Update: I got some time to play with this and looks/feels great to play. Didn't find any issues with the default configuration setup either. I couldn't find any documentation on the sdl website for  SDL_GameControllerRumble()... I assume the last parameter we pass into that is the rumble strength? I tried using both an xbox series x controller and a switch pro controller and the rumble on the xbox controller felt weaker than the pro controller. Do you think this is something we should add an RC variable to control? I think that way it's a bit more configurable by the end user per controller, versus having them have to rebuild the binary themselves. (maybe "rumble_strength" or something along those lines)

Let me know your thoughts.

Thanks

Alex

**Comment by Ryzee119** [comment]
Thanks for the prompt review and test! SDL_GameControllerRumble has the following definition

```
/**
 *  Trigger a rumble effect
 *  Each call to this function cancels any previous rumble effect, and calling it with 0 intensity stops any rumbling.
 *
 *  \param gamecontroller The controller to vibrate
 *  \param low_frequency_rumble The intensity of the low frequency (left) rumble motor, from 0 to 0xFFFF
 *  \param high_frequency_rumble The intensity of the high frequency (right) rumble motor, from 0 to 0xFFFF
 *  \param duration_ms The duration of the rumble effect, in milliseconds
 *
 *  \return 0, or -1 if rumble isn't supported on this joystick
 */
```

I think adding some kind of rumble_strength percentage is a good idea. I can look into that as soon as I can. Not sure im happy with the 50ms I just put in there. I assume the gameboy actually will just stay rumbling unless otherwise told. I can look into this unless you have a better number in mind.

**Comment by Ryzee119** [comment]
I should also make it only send rumble commands if its MBC5 and the rumble state changes. Currently it spams the controller.

**Comment by AlexOberhofer** [comment]
Good call - I only tested it with Pokemon Pinball :). Maybe have a rumble_enable flag that we set in the case that we have an MBC5 + Rumble ROM? 

As far as how the gameboy actually handles rumble I'm not sure either without doing research of my own. As long as we have something that "feels right" I think we should be good. Whatever you think reasonable defaults are for now we can roll with and tweak as needed.

**Comment by AlexOberhofer** [comment]
I did a quick search of the pandocs for rumble info but I didn't really see anything besides which ROM types support it. My guess would be that it rumbles until that rumble bit is reset, but if you find something definitive please share it. If we have to best guess on simulating it I think all will be ok

**Comment by Ryzee119** [comment]
I pushed some updates to this. It now reads in a variable called `rumble_strength` which is a value from 0 to 100%. 0% will disable the rumble feature.

It now only sends  rumble commands if a rumble MBC is detected and the value has actually changed. This prevents spamming the controller constantly.

I changed that 50ms, to 250ms based on some research of other gb emulators. i.e. https://github.com/LIJI32/SameBoy/blob/925bd863c08334b54cd075b6da9e537688ecb76b/SDL/main.c#L375

I realised joy_exports wasnt parsed properly either so now they should work in the rc files.

**Comment by AlexOberhofer** [comment]
Awesome work again Ryzee. I'll play with this some today and merge it in if I don't find any issues. Code changes look good though.

I still probably want to bring back using the controller sticks for Dpad movement, but I think using a new implementation and not the wonky one I had before is probably the way to go. Probably something for another PR unless you wanted to take a stab at it in this one.

Thanks again!

Alex

**Comment by Ryzee119** [comment]
I can add analog stick dpad mapping back in the next day or so :smile: Ill push to this PR

**Comment by AlexOberhofer** [comment]
Sweet! Will keep an eye out for more pushes

**Comment by Ryzee119** [comment]
Ive pushed joy left axis to dpad conversion (plus a general cleanup). This was a bit trickier than I initially thought with x and y axis and managing press and release events properly, but I got there in a reasonably concise way I hope.

gamecontroller remapping works now too via rc file now.

**Comment by AlexOberhofer** [comment]
Yeah I ran into some similar problems with managing the press/release events but I played with it some this morning and it feels pretty good. It's not like the Gameboy had a joystick for us to emulate so I think what you've got here looks good. I'm good to merge this branch in unless you have anything else you want to add.

**Comment by Ryzee119** [comment]
Dont think I have anything more at this stage on input! I should get back to my xbox port now lol

**Comment by AlexOberhofer** [comment]
Merged in. Thanks for all the contributions and keep me posted on the port!

Alex

**Pull request merged**
